name: Run Gatus
on: workflow_dispatch
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: twinproduction/gatus:latest
      #env:
      #  NODE_ENV: development
      ports:
        - 8080:8080
      volumes:
        - ./config:/config
      #options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
